extendedweb:
    build: .
    ports:
        - "8082:80"
    links:
        - mysqldb
    command: /usr/bin/supervisord

mysqldb:
    image: 'mysql:5.5'
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=basilisk
        - MYSQL_DATABASE=extended
