version: "2"
services:
  extendedweb:
    container_name: extstats-web
    build: .
    ports:
        - "80:80"
    links:
        - mysqldb
    command: /usr/bin/supervisord
    depends_on:
      - mysqldb

  mysqldb:
    image: 'mysql:5.5'
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=basilisk
        - MYSQL_DATABASE=extended
        - TZ=America/New_York
    container_name: extstats-db
    volumes:
      - extstats-data:/var/lib/mysql
volumes:
  extstats-data:
